### ISSUE TITLE
CB-Social media cover and post @Thaanu2001

### ISSUE THREAD

**Issue by Dinushi94** [Satriaana/Community-Buildup#1]

**Comment by uvinduperera** [comment]
This should be on the designing board

**Comment by uvinduperera** [comment]
@Dinushi94 ?

**Comment by Thaanu2001** [comment]
I have already created this in the design board

**Comment by uvinduperera** [comment]
Ah, I think this is the copy for the communty buildup. This should be assinged for someone in the @Satriaana/community-buildup-team. So he or she will be the one who handel this issue. (Informing DT (design team) by **adding a note to their kanban**, get the updates, and **close this issue**)  DT team will assign someone. Just create a note in thier kanban and get the updates :D

**Comment by Thaanu2001** [comment]
Cover Designs uploaded to [Design Repo](https://github.com/Satriaana/Design/tree/main/Social%20Media%20Covers)

**Comment by uvinduperera** [comment]
I will close the issue as it's done
