### ISSUE TITLE
**Critical** Please do this task before this weekly meeting

### ISSUE THREAD

**Issue by Dinushi94** [Satriaana/Community-Buildup#18]
- [x] Change the team Kanban board to be suited for the volunteer onboard process
  - [x] blog
  - [x] dev
  - [x] design
  - [x] DevOps

- [x] Assign one or two members for volunteer onboard process 
  - [x] blog
  - [x] dev
  - [x] design
  - [x] DevOps

@Satriaana/community-buildup-team @Satriaana/blog-team 
@Satriaana/design-team 
@Satriaana/development-team
@Satriaana/development-team
@Satriaana/devops

**Comment by uvinduperera** [comment]
From @Satriaana/devops ;

We have created **CB-VOL temp column** to add volunteer onboarding tasks. Please use this column for related tasks. Day to day activities will be managed as usual in the _"issues"_ column 

For VOL onboard related tasks please directly contact me

**Comment by SenaliMadawala** [comment]
**From** @Satriaana/blog-team 
We created a column in Blog project for volunteer onboarding tasks as **CB-VOL**. So now anyone can use that column for those tasks.

Contact for the volunteer onboarding process tasks:- 
@ChamodiePubudini  
@SenaliMadawala

**Comment by Thaanu2001** [comment]
From @Satriaana/design-team 
We created the **CB-VOL** column in the Design Project for the volunteer onboard process. Please use that column for those tasks.

Two members for volunteer onboard process -
@Thaanu2001 
@nimeshkavinda

**Comment by Thaanu2001** [comment]
From @Satriaana/development-team 
We created the CB-VOL column in the Development Project for the volunteer onboard process. Please use that column for those tasks.

Two members for volunteer onboard process -
@Mewni

**Comment by Dinushi94** [comment]
Done
