### ISSUE TITLE
Template for weekly progression

### ISSUE THREAD

**Issue by Dinushi94** [Satriaana/Community-Buildup#20]

**Comment by uvinduperera** [comment]
This should be done and send to @Mewni asap

**Comment by SenaliMadawala** [comment]
Here is the template I made. So please check this temporary document to finalize this task or add them if you have anything to add. (Maybe there are some mistakes in this template. If so, please let me know) @Satriaana/community-buildup-team 

[Template for weekly progression](https://docs.google.com/document/d/1GJ1S2G7L1nC23wyyTvamC3hmYyGGErnamFqA1MDwYxE/edit?usp=sharingl)

**Comment by uvinduperera** [comment]
Great !

**Comment by SenaliMadawala** [comment]
I updated this template to the core repo as an md file. Please go and check.

[Template for weekly progression](https://github.com/Satriaana/Core/blob/main/Template%20for%20weekly%20progression.md)
