### ISSUE TITLE
Project Management Team

### ISSUE THREAD

**Issue by ChamodiePubudini** [Satriaana/Community-Buildup#34]
- [x] Make a slack channel
- [x] Make a category in Forum
- [x] Make a team in GitHub teams and GitHub Projects
- [x] Assign a Team Lead
- [ ] Assign members

**Comment by Dinushi94** [comment]
I think very core members should assign the this team. We need a team lead.

**Comment by Dinushi94** [comment]
Team Lead @AmandaS98
